version: '3.1'


services:
  base_pg:
    image: postgres:15.1
    container_name: base_pg
    restart: always
    environment:
      POSTGRES_DB: basepg
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: secret1234
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432